env:
  CIRRUS_AGENT_VERSION: 1.96.2

pipe:
  name: Build Site and Validate Links
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  allow_failures: true
  steps:
    - image: ghcr.io/squidfunk/mkdocs-material:latest
      install_script: python3 -m pip install --upgrade -r requirements.txt
      build_script: mkdocs build
      site_artifacts:
        path: "site/**"
    - image: fkorotkov/liche:latest
      validate_script: /liche --concurrency 2 --document-root=site --recursive site/
